### ISSUE TITLE
Installing U-Boot

### ISSUE THREAD

**Issue by maitiSoutrik** [PacktPublishing/Mastering-Embedded-Linux-Programming-Second-Edition#3]
I am currently stuck in this Chapter.
I am using the following:

lspci gives 

00:00.0 Host bridge: Intel Corporation 8th Gen Core Processor Host Bridge/DRAM Registers (rev 08)
00:02.0 VGA compatible controller: Intel Corporation Iris Plus Graphics 655 (rev 01)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model
00:12.0 Signal processing controller: Intel Corporation Cannon Point-LP Thermal Controller (rev 30)
00:14.0 USB controller: Intel Corporation Cannon Point-LP USB 3.1 xHCI Controller (rev 30)
00:14.2 RAM memory: Intel Corporation Cannon Point-LP Shared SRAM (rev 30)
00:14.3 Network controller: Intel Corporation Cannon Point-LP CNVi [Wireless-AC] (rev 30)
00:16.0 Communication controller: Intel Corporation Cannon Point-LP MEI Controller #1 (rev 30)
00:17.0 SATA controller: Intel Corporation Cannon Point-LP SATA Controller [AHCI Mode] (rev 30)
00:1c.0 PCI bridge: Intel Corporation Cannon Point-LP PCI Express Root Port #1 (rev f0)
00:1c.4 PCI bridge: Intel Corporation Cannon Point-LP PCI Express Root Port #5 (rev f0)
00:1d.0 PCI bridge: Intel Corporation Cannon Point-LP PCI Express Root Port #9 (rev f0)
00:1d.6 PCI bridge: Intel Corporation Cannon Point-LP PCI Express Root Port #15 (rev f0)
00:1f.0 ISA bridge: Intel Corporation Cannon Point-LP LPC Controller (rev 30)
00:1f.3 Audio device: Intel Corporation Cannon Point-LP High Definition Audio Controller (rev 30)
00:1f.4 SMBus: Intel Corporation Cannon Point-LP SMBus Controller (rev 30)
00:1f.5 Serial bus controller [0c80]: Intel Corporation Cannon Point-LP SPI Controller (rev 30)
00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection (6) I219-V (rev 30)
6d:00.0 Non-Volatile memory controller: Phison Electronics Corporation E12 NVMe Controller (rev 01)
6e:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS522A PCI Express Card Reader (rev 01)

--------------------------------------------------------------------------------------------------------------------

My card reader is not working on this host so I used an external usb card reader:

lsblk yields:

NAME                      MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0                       7:0    0    55M  1 loop /snap/core18/1880
loop1                       7:1    0  55.4M  1 loop /snap/core18/1944
loop2                       7:2    0  71.3M  1 loop /snap/lxd/16099
loop3                       7:3    0  29.9M  1 loop /snap/snapd/8542
loop4                       7:4    0  67.8M  1 loop /snap/lxd/18150
loop5                       7:5    0  31.1M  1 loop /snap/snapd/10492
sdb                         8:16   1 119.4G  0 disk 
└─sdb1                      8:17   1 119.4G  0 part 
nvme0n1                   259:0    0 238.5G  0 disk 
├─nvme0n1p1               259:1    0   512M  0 part /boot/efi
├─nvme0n1p2               259:2    0     1G  0 part /boot
└─nvme0n1p3               259:3    0   237G  0 part 
  └─ubuntu--vg-ubuntu--lv 253:0    0 118.5G  0 lvm  /

--------------------------------------------------------------------------------------------------

I am trying to mount sdb1 (which is my sd card ) to /media/sdcard :

----------------------------------------------------------------------
sudo mount /dev/sdb1 /media/sdcard/

FUSE exfat 1.3.0
WARN: volume was not unmounted cleanly.

----------------------------------------------------------------------

sudo Mastering-Embedded-Linux-Programming-Second-Edition/format-sdcard.sh sdb1

Drive does not exist

------------------------------------------------------------------------------

I am sure someone can help me out so that I may be able to proceed.
This book needs a revision since there's a lot of things a reader has to debug while reading through and trying out

**Comment by maitiSoutrik** [comment]
I was able to make some changes and solve the above problem but now serial logs show me the following when I am trying to follow the steps as mentioned in the book.
U-Boot 2017.01 (Jan 02 2021 - 22:02:25 +0000)

CPU  : AM335X-GP rev 2.1
I2C:   ready
DRAM:  512 MiB
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
*** Warning - bad CRC, using default environment

<ethaddr> not set. Validating first E-fuse MAC
Net:   cpsw, usb_ether
Press SPACE to abort autoboot in 2 seconds
switch to partitions #0, OK
mmc0 is current device
SD/MMC found on device 0
reading boot.scr
** Unable to read file boot.scr **
reading uEnv.txt
** Unable to read file uEnv.txt **
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
switch to partitions #0, OK
mmc0 is current device
SD/MMC found on device 0
** File not found /boot/zImage **
switch to partitions #0, OK
mmc1(part 0) is current device
Scanning mmc 1:1...
switch to partitions #0, OK
mmc1(part 0) is current device
SD/MMC found on device 1
** Invalid partition 2 **
## Error: "bootcmd_nand0" not defined
starting USB...
USB0:   Port not available.
cpsw Waiting for PHY auto negotiation to complete......... TIMEOUT !
BOOTP broadcast 1
data abort
pc : [<9ff871ba>]	   lr : [<000019bd>]
reloc pc : [<808351ba>]	   lr : [<e08af9bd>]
sp : 9df31908  ip : 00000000	 fp : 9ffec948
r10: 00000000  r9 : 9df31ed8	 r8 : 9ffec490
r7 : 9ffee7d4  r6 : 0000000e	 r5 : 00000000  r4 : 9ffec98e
r3 : 00060101  r2 : 00000000	 r1 : 9ffec94e  r0 : 0000000e
Flags: nzCv  IRQs off  FIQs on  Mode SVC_32
Resetting CPU ...

resetting ...

**Comment by csimmonds** [comment]
Hi, I am the author of the book. I am sorry that you are having problems with the U-Boot section.

The key line in the console output above is "Press SPACE to abort autoboot in 2 seconds". If you do press the space bar at that time window you will get to the U-Boot prompt and you can continue as described on page 65.

At some point in the past the implementation of U-Boot for BeagleBone would display a command line prompt after it failed to load a operating system, but the version we are using here (2017.01) reboots. I seems that I did not pick that up for the 2nd ed

BR,
Chris Simmonds

**Comment by maitiSoutrik** [comment]
Hi Chris,
Thanks a lot.
I will try it.
Regards
Soutrik

**Comment by ManikandanKurup-Packt** [comment]
Hi @maitiSoutrik 
Is the problem resolved? If so, can we close the issue?

Thanks

**Comment by maitiSoutrik** [comment]
Hi @ManikandanKurup-Packt ,
I haven't got a chance to try it out yet.
Please go ahead and close the ticket as of now.
I can reopen it if I get stuck again.

Thanks

**Comment by ManikandanKurup-Packt** [comment]
Thank you @maitiSoutrik. Feel free to open this issue if you get stuck and feel free to reach out to me in case if you need any help.

**Comment by maitiSoutrik** [comment]
Thanks a lot for the support.
